"""
CRAFT Fingerprint Schema - 256-Bit Bio-Context Fingerprint Definition

Every bit position is explicitly defined, biologically justified, and traceable
to a public database source. The schema is divided into 4 modules of 64 bits each:

  Module A [0-63]:   Membrane Topology & Localization
  Module B [64-127]:  Signal Transduction Mechanism
  Module C [128-191]: Binding Pocket Character
  Module D [192-255]: Endogenous Ligand Type

Each module has 4 sub-blocks of 16 bits for hierarchical organization.

Data sources:
  - uniprot:  UniProt REST API (subcellular localization, topology, keywords)
  - iuphar:   IUPHAR/BPS Guide to Pharmacology (target class, signaling, ligands)
  - chembl:   ChEMBL (target classification, bioactivity context)
  - pocket:   Binding pocket analysis (PDB-based or class-based fallback)
  - derived:  Inferred from combination of sources

Author: Dr. Salah - Insilico Sigma Lab
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass(frozen=True)
class BitDefinition:
    """Definition of a single bit position in the CRAFT fingerprint."""
    position: int           # 0-255 absolute position
    module: str             # 'A', 'B', 'C', 'D'
    name: str               # Machine-readable short name (unique)
    description: str        # Human-readable description
    data_source: str        # 'uniprot', 'iuphar', 'chembl', 'pocket', 'derived'
    category: str           # Sub-category within module
    biological_basis: str = ''  # Brief justification for inclusion


# ==============================================================================
# MODULE A: Membrane Topology & Localization (bits 0-63)
# ==============================================================================
# Encodes WHERE in the cell the drug must reach and how the target is organized.
# This determines drug delivery requirements: membrane permeability, BBB crossing,
# nuclear access, mitochondrial targeting, etc.

MODULE_A_BITS = [
    # --- Sub-block A1: Subcellular Localization (bits 0-15) ---
    # Directly from UniProt subcellular location annotations
    BitDefinition(0, 'A', 'extracellular', 'Target is extracellular / secreted',
                  'uniprot', 'localization',
                  'Drug does not need to cross membranes'),
    BitDefinition(1, 'A', 'cell_surface', 'Target is on cell surface (accessible from outside)',
                  'uniprot', 'localization',
                  'Antibodies and large molecules can reach'),
    BitDefinition(2, 'A', 'plasma_membrane', 'Target is integral to plasma membrane',
                  'uniprot', 'localization',
                  'Transmembrane domain involvement'),
    BitDefinition(3, 'A', 'peripheral_membrane', 'Peripheral membrane association (not transmembrane)',
                  'uniprot', 'localization',
                  'Lipid-anchored or electrostatic association'),
    BitDefinition(4, 'A', 'cytoplasm', 'Target is cytoplasmic / cytosolic',
                  'uniprot', 'localization',
                  'Drug must cross plasma membrane'),
    BitDefinition(5, 'A', 'nucleus', 'Target is nuclear',
                  'uniprot', 'localization',
                  'Drug must cross two membranes + nuclear pore'),
    BitDefinition(6, 'A', 'mitochondria', 'Target is mitochondrial',
                  'uniprot', 'localization',
                  'Drug must cross mitochondrial membranes; cationic accumulation'),
    BitDefinition(7, 'A', 'endoplasmic_reticulum', 'Target is in ER',
                  'uniprot', 'localization',
                  'ER-resident enzymes, CYPs, protein folding'),
    BitDefinition(8, 'A', 'golgi', 'Target is in Golgi apparatus',
                  'uniprot', 'localization',
                  'Post-translational modification enzymes'),
    BitDefinition(9, 'A', 'lysosome', 'Target is lysosomal / endosomal',
                  'uniprot', 'localization',
                  'Acid-trapping relevant for cationic amphiphilic drugs'),
    BitDefinition(10, 'A', 'endosome', 'Target is in endosomes',
                   'uniprot', 'localization',
                   'Endosomal escape relevant for biologics'),
    BitDefinition(11, 'A', 'peroxisome', 'Target is peroxisomal',
                   'uniprot', 'localization',
                   'Fatty acid oxidation enzymes'),
    BitDefinition(12, 'A', 'cytoskeleton', 'Target is cytoskeletal',
                   'uniprot', 'localization',
                   'Structural proteins, tubulin, actin'),
    BitDefinition(13, 'A', 'synapse', 'Target is synaptic / presynaptic / postsynaptic',
                   'uniprot', 'localization',
                   'Neurotransmitter receptors and transporters'),
    BitDefinition(14, 'A', 'cell_junction', 'Target is at cell junctions',
                   'uniprot', 'localization',
                   'Tight junctions, gap junctions, desmosomes'),
    BitDefinition(15, 'A', 'secretory_vesicle', 'Target is in secretory vesicles',
                   'uniprot', 'localization',
                   'Vesicular transporters, neurotransmitter packaging'),

    # --- Sub-block A2: Transmembrane Topology (bits 16-31) ---
    BitDefinition(16, 'A', 'single_pass_type_i', 'Single-pass type I transmembrane (N-extra, C-cyto)',
                   'uniprot', 'topology',
                   'RTKs, single-pass receptors'),
    BitDefinition(17, 'A', 'single_pass_type_ii', 'Single-pass type II transmembrane (N-cyto, C-extra)',
                   'uniprot', 'topology',
                   'Transferrin receptor type'),
    BitDefinition(18, 'A', 'multi_pass_tm', 'Multi-pass transmembrane (2-6 TM helices)',
                   'uniprot', 'topology',
                   'Transporters, channels with moderate TM count'),
    BitDefinition(19, 'A', 'seven_tm', '7-transmembrane domain (GPCR signature)',
                   'uniprot', 'topology',
                   'G-protein coupled receptor topology'),
    BitDefinition(20, 'A', 'gpi_anchored', 'GPI-anchored to membrane',
                   'uniprot', 'topology',
                   'Ecto-enzymes, cell surface markers'),
    BitDefinition(21, 'A', 'lipid_anchored', 'Lipid-anchored (farnesyl, myristoyl, palmitoyl)',
                   'uniprot', 'topology',
                   'RAS family, Src family kinases'),
    BitDefinition(22, 'A', 'soluble_protein', 'Soluble protein (no membrane association)',
                   'uniprot', 'topology',
                   'Cytosolic enzymes, transcription factors'),
    BitDefinition(23, 'A', 'tm_helix_1_2', '1-2 transmembrane helices',
                   'uniprot', 'topology',
                   'Simple single/double-pass topology'),
    BitDefinition(24, 'A', 'tm_helix_3_6', '3-6 transmembrane helices',
                   'uniprot', 'topology',
                   'Moderate complexity: some transporters'),
    BitDefinition(25, 'A', 'tm_helix_7_plus', '7+ transmembrane helices',
                   'uniprot', 'topology',
                   'GPCRs, complex transporters'),
    BitDefinition(26, 'A', 'binding_site_extracellular', 'Binding site faces extracellular space',
                   'derived', 'topology',
                   'Drug accessibility from plasma'),
    BitDefinition(27, 'A', 'binding_site_intracellular', 'Binding site faces intracellular space',
                   'derived', 'topology',
                   'Drug must cross membrane to reach binding site'),
    BitDefinition(28, 'A', 'binding_site_within_membrane', 'Binding site within membrane bilayer',
                   'derived', 'topology',
                   'Lipophilic access pathway'),
    BitDefinition(29, 'A', 'homo_oligomer', 'Functions as homo-oligomer (dimer, tetramer)',
                   'uniprot', 'topology',
                   'Cooperativity, multiple binding sites'),
    BitDefinition(30, 'A', 'hetero_oligomer', 'Functions as hetero-oligomer complex',
                   'uniprot', 'topology',
                   'Subunit-selective pharmacology possible'),
    BitDefinition(31, 'A', 'disulfide_stabilized', 'Disulfide-bond stabilized extracellular domain',
                   'uniprot', 'topology',
                   'Structural rigidity of extracellular binding domain'),

    # --- Sub-block A3: Tissue Expression & BBB (bits 32-47) ---
    BitDefinition(32, 'A', 'ubiquitous_expression', 'Ubiquitously expressed across tissues',
                   'uniprot', 'expression',
                   'Off-target toxicity risk is high'),
    BitDefinition(33, 'A', 'brain_enriched', 'Brain / CNS enriched expression',
                   'uniprot', 'expression',
                   'Drug must cross BBB; CNS side effects possible'),
    BitDefinition(34, 'A', 'liver_enriched', 'Liver enriched expression',
                   'uniprot', 'expression',
                   'First-pass metabolism relevant'),
    BitDefinition(35, 'A', 'kidney_enriched', 'Kidney enriched expression',
                   'uniprot', 'expression',
                   'Renal clearance target'),
    BitDefinition(36, 'A', 'heart_enriched', 'Heart / cardiac enriched',
                   'uniprot', 'expression',
                   'Cardiotoxicity risk assessment'),
    BitDefinition(37, 'A', 'immune_enriched', 'Immune cell enriched (lymphocytes, macrophages)',
                   'uniprot', 'expression',
                   'Immunomodulatory target'),
    BitDefinition(38, 'A', 'lung_enriched', 'Lung enriched expression',
                   'uniprot', 'expression',
                   'Inhalation delivery relevant'),
    BitDefinition(39, 'A', 'gi_tract_enriched', 'GI tract enriched expression',
                   'uniprot', 'expression',
                   'Oral bioavailability relevant'),
    BitDefinition(40, 'A', 'endocrine_enriched', 'Endocrine tissue enriched',
                   'uniprot', 'expression',
                   'Hormonal regulation targets'),
    BitDefinition(41, 'A', 'muscle_enriched', 'Skeletal / smooth muscle enriched',
                   'uniprot', 'expression',
                   'Myopathy risk'),
    BitDefinition(42, 'A', 'skin_enriched', 'Skin / dermal enriched',
                   'uniprot', 'expression',
                   'Topical delivery potential'),
    BitDefinition(43, 'A', 'bone_marrow_enriched', 'Bone marrow / hematopoietic enriched',
                   'uniprot', 'expression',
                   'Hematological toxicity risk'),
    BitDefinition(44, 'A', 'bbb_relevant', 'Target behind blood-brain barrier',
                   'derived', 'expression',
                   'Requires BBB-penetrant drug design'),
    BitDefinition(45, 'A', 'tumor_overexpressed', 'Known to be overexpressed in tumors',
                   'derived', 'expression',
                   'Oncology target; tumor selectivity possible'),
    BitDefinition(46, 'A', 'disease_restricted', 'Expression restricted to disease state',
                   'derived', 'expression',
                   'High selectivity window'),
    BitDefinition(47, 'A', 'developmental_role', 'Essential in embryonic development',
                   'uniprot', 'expression',
                   'Teratogenicity risk'),

    # --- Sub-block A4: Protein Family Classification (bits 48-63) ---
    BitDefinition(48, 'A', 'family_gpcr', 'G-protein coupled receptor',
                   'iuphar', 'family',
                   'Largest druggable target family (~34% of approved drugs)'),
    BitDefinition(49, 'A', 'family_ion_channel', 'Ion channel',
                   'iuphar', 'family',
                   'Ligand-gated, voltage-gated, or mechanosensitive'),
    BitDefinition(50, 'A', 'family_kinase', 'Protein kinase',
                   'uniprot', 'family',
                   'Receptor or non-receptor; ATP-competitive drugs'),
    BitDefinition(51, 'A', 'family_nuclear_receptor', 'Nuclear hormone receptor',
                   'iuphar', 'family',
                   'Transcription factor; genomic and non-genomic signaling'),
    BitDefinition(52, 'A', 'family_transporter', 'Membrane transporter (SLC / ABC)',
                   'iuphar', 'family',
                   'Solute carriers and ABC efflux pumps'),
    BitDefinition(53, 'A', 'family_enzyme', 'Enzyme (non-kinase, non-protease)',
                   'uniprot', 'family',
                   'Metabolic enzymes, oxidoreductases, transferases'),
    BitDefinition(54, 'A', 'family_protease', 'Protease / peptidase',
                   'uniprot', 'family',
                   'Serine, cysteine, metallo, aspartyl proteases'),
    BitDefinition(55, 'A', 'family_phosphatase', 'Phosphatase',
                   'uniprot', 'family',
                   'Signal termination; emerging drug targets'),
    BitDefinition(56, 'A', 'family_ligase', 'E3 ubiquitin ligase',
                   'uniprot', 'family',
                   'PROTAC / molecular glue targets'),
    BitDefinition(57, 'A', 'family_epigenetic', 'Epigenetic regulator (HDAC, HMT, DNMT)',
                   'uniprot', 'family',
                   'Chromatin modifiers, histone code writers/erasers'),
    BitDefinition(58, 'A', 'family_chaperone', 'Molecular chaperone (HSP)',
                   'uniprot', 'family',
                   'Protein folding, HSP90 inhibitors in oncology'),
    BitDefinition(59, 'A', 'family_structural', 'Structural / scaffolding protein',
                   'uniprot', 'family',
                   'Tubulin, actin; cytoskeletal drugs'),
    BitDefinition(60, 'A', 'family_transcription_factor', 'Transcription factor (non-NR)',
                   'uniprot', 'family',
                   'Historically undruggable; PPI disruption approaches'),
    BitDefinition(61, 'A', 'family_gtpase', 'GTPase (RAS, RHO, RAB family)',
                   'uniprot', 'family',
                   'RAS is most mutated oncogene; covalent inhibitors'),
    BitDefinition(62, 'A', 'family_receptor_other', 'Other receptor type (cytokine, death, etc.)',
                   'uniprot', 'family',
                   'Non-GPCR, non-RTK receptors'),
    BitDefinition(63, 'A', 'family_other', 'Other protein family',
                   'uniprot', 'family',
                   'Does not fit standard classifications'),
]


# ==============================================================================
# MODULE B: Signal Transduction Mechanism (bits 64-127)
# ==============================================================================
# Encodes HOW the target propagates its signal after drug binding.
# This determines downstream pharmacology, onset of action, and
# therapeutic vs side-effect profiles.

MODULE_B_BITS = [
    # --- Sub-block B1: Primary Signaling Mechanism (bits 64-79) ---
    BitDefinition(64, 'B', 'gpcr_gs_coupled', 'Gs-coupled (stimulates adenylyl cyclase → cAMP ↑)',
                   'iuphar', 'mechanism',
                   'PKA activation; beta-adrenergic prototype'),
    BitDefinition(65, 'B', 'gpcr_gi_coupled', 'Gi/Go-coupled (inhibits adenylyl cyclase → cAMP ↓)',
                   'iuphar', 'mechanism',
                   'PKA inhibition; opioid, alpha2-adrenergic prototype'),
    BitDefinition(66, 'B', 'gpcr_gq_coupled', 'Gq/G11-coupled (activates PLC → IP3/DAG)',
                   'iuphar', 'mechanism',
                   'PKC activation, intracellular Ca2+ release'),
    BitDefinition(67, 'B', 'gpcr_g12_13_coupled', 'G12/13-coupled (activates RhoGEF)',
                   'iuphar', 'mechanism',
                   'Cytoskeletal remodeling, cell migration'),
    BitDefinition(68, 'B', 'beta_arrestin_signaling', 'Beta-arrestin biased signaling',
                   'iuphar', 'mechanism',
                   'Receptor internalization, MAPK via arrestin scaffold'),
    BitDefinition(69, 'B', 'receptor_tyrosine_kinase', 'Receptor tyrosine kinase (RTK) activity',
                   'iuphar', 'mechanism',
                   'Autophosphorylation → RAS/MAPK/PI3K cascades'),
    BitDefinition(70, 'B', 'non_receptor_tyrosine_kinase', 'Non-receptor tyrosine kinase (Src, JAK)',
                   'iuphar', 'mechanism',
                   'JAK-STAT, Src family signaling'),
    BitDefinition(71, 'B', 'serine_threonine_kinase', 'Serine/threonine kinase activity',
                   'iuphar', 'mechanism',
                   'mTOR, CDK, MAPK cascade members'),
    BitDefinition(72, 'B', 'ligand_gated_ion_flux', 'Ligand-gated ion channel (direct ionic flux)',
                   'iuphar', 'mechanism',
                   'Fast neurotransmission; millisecond response'),
    BitDefinition(73, 'B', 'voltage_gated_ion_flux', 'Voltage-gated ion channel modulation',
                   'iuphar', 'mechanism',
                   'Action potential modulation; cardiac/neural'),
    BitDefinition(74, 'B', 'transporter_slc', 'SLC transporter (substrate co-transport)',
                   'iuphar', 'mechanism',
                   'Neurotransmitter reuptake, nutrient transport'),
    BitDefinition(75, 'B', 'transporter_abc', 'ABC transporter (ATP-driven efflux/influx)',
                   'iuphar', 'mechanism',
                   'P-gp, MRP, BCRP; drug resistance mechanism'),
    BitDefinition(76, 'B', 'nuclear_receptor_genomic', 'Nuclear receptor (genomic / transcriptional)',
                   'iuphar', 'mechanism',
                   'Transcription factor activation; slow onset (hours)'),
    BitDefinition(77, 'B', 'nuclear_receptor_non_genomic', 'Nuclear receptor (rapid non-genomic effects)',
                   'iuphar', 'mechanism',
                   'Membrane-associated rapid signaling by NRs'),
    BitDefinition(78, 'B', 'enzymatic_catalysis', 'Direct enzymatic catalysis (no signaling cascade)',
                   'derived', 'mechanism',
                   'Metabolic enzymes, CYPs, COX'),
    BitDefinition(79, 'B', 'proteolytic_cleavage', 'Signal through proteolytic cleavage',
                   'derived', 'mechanism',
                   'Caspases, ACE, renin, coagulation factors'),

    # --- Sub-block B2: Downstream Pathways & Second Messengers (bits 80-95) ---
    BitDefinition(80, 'B', 'pathway_camp', 'cAMP second messenger pathway',
                   'iuphar', 'pathway',
                   'Adenylyl cyclase → cAMP → PKA'),
    BitDefinition(81, 'B', 'pathway_calcium', 'Intracellular calcium signaling',
                   'iuphar', 'pathway',
                   'IP3-mediated Ca2+ release; CaM-dependent kinases'),
    BitDefinition(82, 'B', 'pathway_mapk_erk', 'MAPK/ERK cascade',
                   'derived', 'pathway',
                   'RAS → RAF → MEK → ERK; proliferation'),
    BitDefinition(83, 'B', 'pathway_pi3k_akt', 'PI3K/Akt/mTOR pathway',
                   'derived', 'pathway',
                   'Cell survival, growth, metabolism'),
    BitDefinition(84, 'B', 'pathway_jak_stat', 'JAK-STAT pathway',
                   'derived', 'pathway',
                   'Cytokine receptor signaling; immune regulation'),
    BitDefinition(85, 'B', 'pathway_nfkb', 'NF-kB pathway',
                   'derived', 'pathway',
                   'Inflammatory and immune gene transcription'),
    BitDefinition(86, 'B', 'pathway_wnt', 'Wnt / beta-catenin pathway',
                   'derived', 'pathway',
                   'Stem cell maintenance, development, cancer'),
    BitDefinition(87, 'B', 'pathway_notch', 'Notch signaling pathway',
                   'derived', 'pathway',
                   'Cell fate determination, T-cell development'),
    BitDefinition(88, 'B', 'pathway_hedgehog', 'Hedgehog signaling pathway',
                   'derived', 'pathway',
                   'Development, basal cell carcinoma'),
    BitDefinition(89, 'B', 'pathway_tgfb_smad', 'TGF-beta / SMAD pathway',
                   'derived', 'pathway',
                   'Fibrosis, immune suppression, EMT'),
    BitDefinition(90, 'B', 'pathway_dna_damage', 'DNA damage response pathway',
                   'derived', 'pathway',
                   'ATM/ATR, p53, PARP; genotoxic drugs'),
    BitDefinition(91, 'B', 'pathway_apoptosis', 'Apoptosis pathway (intrinsic or extrinsic)',
                   'derived', 'pathway',
                   'Caspase cascade, Bcl-2 family, death receptors'),
    BitDefinition(92, 'B', 'pathway_autophagy', 'Autophagy pathway',
                   'derived', 'pathway',
                   'mTOR-regulated; lysosomal degradation'),
    BitDefinition(93, 'B', 'pathway_ubiquitin_proteasome', 'Ubiquitin-proteasome pathway',
                   'derived', 'pathway',
                   'Proteasomal degradation; PROTAC mechanism'),
    BitDefinition(94, 'B', 'pathway_ip3_dag', 'IP3/DAG second messenger',
                   'iuphar', 'pathway',
                   'PLC-mediated; PKC activation'),
    BitDefinition(95, 'B', 'pathway_cgmp', 'cGMP second messenger',
                   'iuphar', 'pathway',
                   'Guanylyl cyclase, PDE5, NO signaling'),

    # --- Sub-block B3: Signal Dynamics & Kinetics (bits 96-111) ---
    BitDefinition(96, 'B', 'fast_signaling', 'Fast signaling (milliseconds to seconds)',
                   'derived', 'dynamics',
                   'Ion channels, ionotropic receptors'),
    BitDefinition(97, 'B', 'medium_signaling', 'Medium signaling (seconds to minutes)',
                   'derived', 'dynamics',
                   'GPCR-mediated second messengers'),
    BitDefinition(98, 'B', 'slow_signaling', 'Slow signaling (hours to days)',
                   'derived', 'dynamics',
                   'Nuclear receptors, transcriptional regulation'),
    BitDefinition(99, 'B', 'signal_amplification', 'Signal amplification cascade (high gain)',
                   'derived', 'dynamics',
                   'Kinase cascades amplify signal >1000-fold'),
    BitDefinition(100, 'B', 'negative_feedback', 'Known negative feedback regulation',
                    'derived', 'dynamics',
                    'Receptor desensitization, phosphatase antagonism'),
    BitDefinition(101, 'B', 'receptor_desensitization', 'Receptor desensitization / tachyphylaxis',
                    'iuphar', 'dynamics',
                    'GRK phosphorylation, arrestin-mediated internalization'),
    BitDefinition(102, 'B', 'receptor_internalization', 'Ligand-induced receptor internalization',
                    'iuphar', 'dynamics',
                    'Clathrin-mediated endocytosis of receptor'),
    BitDefinition(103, 'B', 'constitutive_activity', 'Constitutively active (basal activity without ligand)',
                    'iuphar', 'dynamics',
                    'Inverse agonism possible; baseline signaling'),
    BitDefinition(104, 'B', 'allosteric_modulation', 'Allosteric modulation possible',
                    'iuphar', 'dynamics',
                    'PAM/NAM pharmacology; ceiling effect'),
    BitDefinition(105, 'B', 'biased_agonism', 'Biased agonism documented',
                    'iuphar', 'dynamics',
                    'Pathway-selective activation possible'),
    BitDefinition(106, 'B', 'irreversible_binding', 'Irreversible / covalent binding known',
                    'derived', 'dynamics',
                    'Covalent inhibitors; duration-of-action advantage'),
    BitDefinition(107, 'B', 'cooperative_binding', 'Cooperative binding (Hill coefficient > 1)',
                    'derived', 'dynamics',
                    'Ultrasensitive dose-response'),
    BitDefinition(108, 'B', 'dimerization_dependent', 'Signaling requires receptor dimerization',
                    'derived', 'dynamics',
                    'RTK dimerization, GPCR heterodimerization'),
    BitDefinition(109, 'B', 'scaffold_protein_dependent', 'Signaling requires scaffold proteins',
                    'derived', 'dynamics',
                    'AKAP, beta-arrestin scaffold'),
    BitDefinition(110, 'B', 'cross_talk_documented', 'Cross-talk with other signaling pathways',
                    'derived', 'dynamics',
                    'GPCR-RTK cross-talk, MAPK-NF-kB integration'),
    BitDefinition(111, 'B', 'therapeutic_modulation_type', 'Target modulated therapeutically (not just inhibited)',
                    'derived', 'dynamics',
                    'Agonists, antagonists, modulators all relevant'),

    # --- Sub-block B4: Tissue-Specific Signaling Context (bits 112-127) ---
    BitDefinition(112, 'B', 'cns_signaling', 'CNS-specific signaling context',
                    'derived', 'tissue_signal',
                    'Neurotransmission, synaptic plasticity'),
    BitDefinition(113, 'B', 'cardiac_signaling', 'Cardiac-specific signaling',
                    'derived', 'tissue_signal',
                    'hERG risk, cardiac contractility, arrhythmia'),
    BitDefinition(114, 'B', 'immune_signaling', 'Immune cell signaling',
                    'derived', 'tissue_signal',
                    'T-cell activation, cytokine release, inflammation'),
    BitDefinition(115, 'B', 'metabolic_signaling', 'Metabolic signaling (liver, adipose, pancreas)',
                    'derived', 'tissue_signal',
                    'Insulin, glucagon, lipid metabolism'),
    BitDefinition(116, 'B', 'endocrine_signaling', 'Endocrine signaling',
                    'derived', 'tissue_signal',
                    'Hormonal feedback loops'),
    BitDefinition(117, 'B', 'vascular_signaling', 'Vascular signaling (endothelial, smooth muscle)',
                    'derived', 'tissue_signal',
                    'Blood pressure, angiogenesis'),
    BitDefinition(118, 'B', 'renal_signaling', 'Renal signaling',
                    'derived', 'tissue_signal',
                    'Electrolyte balance, diuretics'),
    BitDefinition(119, 'B', 'oncogenic_signaling', 'Oncogenic signaling role',
                    'derived', 'tissue_signal',
                    'Driver mutation, oncogene addiction'),
    BitDefinition(120, 'B', 'anti_apoptotic', 'Anti-apoptotic role',
                    'derived', 'tissue_signal',
                    'Cell survival signaling; cancer relevance'),
    BitDefinition(121, 'B', 'pro_inflammatory', 'Pro-inflammatory signaling',
                    'derived', 'tissue_signal',
                    'Cytokine production, NF-kB, COX-2'),
    BitDefinition(122, 'B', 'anti_inflammatory', 'Anti-inflammatory signaling',
                    'derived', 'tissue_signal',
                    'Glucocorticoid receptor, IL-10 pathway'),
    BitDefinition(123, 'B', 'neurodegenerative', 'Neurodegeneration-associated signaling',
                    'derived', 'tissue_signal',
                    'Amyloid, tau, alpha-synuclein pathways'),
    BitDefinition(124, 'B', 'fibrotic_signaling', 'Fibrosis-associated signaling',
                    'derived', 'tissue_signal',
                    'TGF-beta, CTGF, collagen deposition'),
    BitDefinition(125, 'B', 'pain_signaling', 'Pain / nociceptive signaling',
                    'derived', 'tissue_signal',
                    'Opioid, TRPV1, Nav1.7, COX pathways'),
    BitDefinition(126, 'B', 'circadian_role', 'Circadian rhythm modulation',
                    'derived', 'tissue_signal',
                    'Melatonin, clock genes'),
    BitDefinition(127, 'B', 'epigenetic_signaling', 'Epigenetic / chromatin signaling',
                    'derived', 'tissue_signal',
                    'Histone modifications, DNA methylation'),
]


# ==============================================================================
# MODULE C: Binding Pocket Character (bits 128-191)
# ==============================================================================
# Encodes the physicochemical nature of the binding site - what chemical
# features a ligand must present to bind effectively.

MODULE_C_BITS = [
    # --- Sub-block C1: Pocket Geometry & Type (bits 128-143) ---
    BitDefinition(128, 'C', 'pocket_deep', 'Deep binding pocket (>8 Angstrom depth)',
                    'pocket', 'geometry',
                    'Requires extended molecules to reach binding residues'),
    BitDefinition(129, 'C', 'pocket_shallow', 'Shallow binding groove (<5 Angstrom)',
                    'pocket', 'geometry',
                    'Fragment-like or flat molecules may bind'),
    BitDefinition(130, 'C', 'pocket_buried', 'Fully buried / enclosed binding site',
                    'pocket', 'geometry',
                    'Ligand encapsulated; desolvation penalty'),
    BitDefinition(131, 'C', 'pocket_surface_exposed', 'Surface-exposed cleft',
                    'pocket', 'geometry',
                    'Solvent-accessible; faster on/off rates'),
    BitDefinition(132, 'C', 'pocket_vol_small', 'Small pocket volume (<200 A3)',
                    'pocket', 'geometry',
                    'Fragment-sized ligands; MW < 250'),
    BitDefinition(133, 'C', 'pocket_vol_medium', 'Medium pocket volume (200-500 A3)',
                    'pocket', 'geometry',
                    'Typical drug-like molecule fits'),
    BitDefinition(134, 'C', 'pocket_vol_large', 'Large pocket volume (500-1000 A3)',
                    'pocket', 'geometry',
                    'Extended scaffolds or macrocycles'),
    BitDefinition(135, 'C', 'pocket_vol_very_large', 'Very large pocket (>1000 A3)',
                    'pocket', 'geometry',
                    'Peptides, PPI interfaces, bivalent ligands'),
    BitDefinition(136, 'C', 'orthosteric_site', 'Orthosteric binding site (endogenous ligand site)',
                    'pocket', 'geometry',
                    'Competitive inhibition/agonism'),
    BitDefinition(137, 'C', 'allosteric_site_known', 'Known allosteric binding site',
                    'pocket', 'geometry',
                    'Non-competitive modulation; ceiling effect'),
    BitDefinition(138, 'C', 'catalytic_active_site', 'Catalytic / active site (enzyme)',
                    'pocket', 'geometry',
                    'Transition state mimics, mechanism-based inhibitors'),
    BitDefinition(139, 'C', 'cryptic_pocket', 'Cryptic pocket (visible only on conformational change)',
                    'pocket', 'geometry',
                    'Accessible through induced fit or population shift'),
    BitDefinition(140, 'C', 'ppi_interface', 'Protein-protein interaction interface',
                    'pocket', 'geometry',
                    'Flat, large surface; challenging for small molecules'),
    BitDefinition(141, 'C', 'atp_binding_site', 'ATP/nucleotide binding site (kinase hinge)',
                    'pocket', 'geometry',
                    'Conserved hinge region; type I kinase inhibitors'),
    BitDefinition(142, 'C', 'substrate_channel', 'Substrate access channel (long tunnel)',
                    'pocket', 'geometry',
                    'CYP active site access; tunnel-shaped'),
    BitDefinition(143, 'C', 'covalent_binding_residue', 'Targetable covalent residue (Cys, Lys, Ser)',
                    'pocket', 'geometry',
                    'Covalent inhibitor warhead target'),

    # --- Sub-block C2: Pocket Polarity & Chemistry (bits 144-159) ---
    BitDefinition(144, 'C', 'pocket_hydrophobic', 'Predominantly hydrophobic pocket',
                    'pocket', 'polarity',
                    'Lipophilic interactions dominate; logP optimization'),
    BitDefinition(145, 'C', 'pocket_polar', 'Predominantly polar pocket',
                    'pocket', 'polarity',
                    'Hydrogen bonding critical; polar surface area'),
    BitDefinition(146, 'C', 'pocket_mixed', 'Mixed hydrophobic/polar character',
                    'pocket', 'polarity',
                    'Amphiphilic ligands preferred'),
    BitDefinition(147, 'C', 'pocket_charged_positive', 'Positively charged environment (Arg, Lys)',
                    'pocket', 'polarity',
                    'Anionic/acidic ligand moieties favored'),
    BitDefinition(148, 'C', 'pocket_charged_negative', 'Negatively charged environment (Asp, Glu)',
                    'pocket', 'polarity',
                    'Cationic/basic ligand moieties favored'),
    BitDefinition(149, 'C', 'pocket_aromatic_rich', 'Aromatic-rich pocket (Phe, Trp, Tyr)',
                    'pocket', 'polarity',
                    'Pi-stacking, cation-pi, CH-pi interactions'),
    BitDefinition(150, 'C', 'hbond_donor_rich', 'H-bond donor residues enriched',
                    'pocket', 'polarity',
                    'Ligand must present acceptors'),
    BitDefinition(151, 'C', 'hbond_acceptor_rich', 'H-bond acceptor residues enriched',
                    'pocket', 'polarity',
                    'Ligand must present donors'),
    BitDefinition(152, 'C', 'metal_coordinating', 'Metal-coordinating site (Zn2+, Mg2+, Fe, Cu)',
                    'pocket', 'polarity',
                    'Metal-binding pharmacophores (hydroxamates, thiols)'),
    BitDefinition(153, 'C', 'backbone_hbond', 'Backbone H-bond interactions dominant',
                    'pocket', 'polarity',
                    'Kinase hinge H-bonds; conserved across family'),
    BitDefinition(154, 'C', 'water_mediated', 'Conserved water-mediated interactions',
                    'pocket', 'polarity',
                    'Structural water molecules bridge ligand-protein'),
    BitDefinition(155, 'C', 'halogen_bond_possible', 'Halogen bonding possible (backbone C=O)',
                    'pocket', 'polarity',
                    'Chloro/bromo substituents can form sigma-hole bonds'),
    BitDefinition(156, 'C', 'pi_cation_possible', 'Cation-pi interaction geometry',
                    'pocket', 'polarity',
                    'Aromatic cage for cationic ligand moiety'),
    BitDefinition(157, 'C', 'disulfide_near_site', 'Disulfide bond near binding site',
                    'pocket', 'polarity',
                    'Structural constraint on pocket flexibility'),
    BitDefinition(158, 'C', 'salt_bridge_critical', 'Salt bridge critical for binding',
                    'pocket', 'polarity',
                    'Ionic interaction anchors ligand'),
    BitDefinition(159, 'C', 'entropy_driven_binding', 'Entropy-driven binding (hydrophobic effect)',
                    'pocket', 'polarity',
                    'Desolvation of hydrophobic surfaces drives affinity'),

    # --- Sub-block C3: Pocket Flexibility & Dynamics (bits 160-175) ---
    BitDefinition(160, 'C', 'pocket_rigid', 'Rigid pocket (low B-factor)',
                    'pocket', 'flexibility',
                    'Lock-and-key binding; SAR is predictable'),
    BitDefinition(161, 'C', 'pocket_semi_flexible', 'Semi-flexible pocket',
                    'pocket', 'flexibility',
                    'Moderate induced fit; adaptive binding'),
    BitDefinition(162, 'C', 'pocket_highly_flexible', 'Highly flexible / disordered region',
                    'pocket', 'flexibility',
                    'Conformational selection; difficult to model'),
    BitDefinition(163, 'C', 'induced_fit', 'Induced-fit mechanism documented',
                    'pocket', 'flexibility',
                    'Ligand binding causes conformational change'),
    BitDefinition(164, 'C', 'conformational_selection', 'Conformational selection mechanism',
                    'pocket', 'flexibility',
                    'Pre-existing conformational ensemble'),
    BitDefinition(165, 'C', 'dfg_motif', 'DFG motif present (kinase)',
                    'pocket', 'flexibility',
                    'DFG-in/DFG-out conformations; type II inhibitors'),
    BitDefinition(166, 'C', 'p_loop', 'P-loop (glycine-rich loop) present',
                    'pocket', 'flexibility',
                    'Kinase P-loop; flexible cap over ATP site'),
    BitDefinition(167, 'C', 'activation_loop', 'Activation loop controls access',
                    'pocket', 'flexibility',
                    'Phosphorylation-dependent pocket accessibility'),
    BitDefinition(168, 'C', 'lid_domain', 'Lid/flap domain covers active site',
                    'pocket', 'flexibility',
                    'HIV protease flaps; dynamic gating'),
    BitDefinition(169, 'C', 'multiple_binding_modes', 'Multiple binding modes observed',
                    'pocket', 'flexibility',
                    'Same ligand can bind in different orientations'),
    BitDefinition(170, 'C', 'high_druggability', 'High druggability score (>0.7)',
                    'pocket', 'flexibility',
                    'Pocket geometry and chemistry support drug-like ligands'),
    BitDefinition(171, 'C', 'medium_druggability', 'Medium druggability score (0.4-0.7)',
                    'pocket', 'flexibility',
                    'Challenging but tractable target'),
    BitDefinition(172, 'C', 'low_druggability', 'Low druggability score (<0.4)',
                    'pocket', 'flexibility',
                    'Difficult target; may need unconventional modalities'),
    BitDefinition(173, 'C', 'pocket_near_membrane', 'Binding pocket near membrane interface',
                    'pocket', 'flexibility',
                    'Lipid bilayer influences ligand access'),
    BitDefinition(174, 'C', 'secondary_pocket', 'Adjacent secondary pocket available',
                    'pocket', 'flexibility',
                    'Extended scaffolds can span both pockets'),
    BitDefinition(175, 'C', 'solvent_exposed_pocket', 'Pocket partially solvent-exposed',
                    'pocket', 'flexibility',
                    'Solvent-facing groups tolerate polar substitution'),

    # --- Sub-block C4: Binding Mode & Mechanism (bits 176-191) ---
    BitDefinition(176, 'C', 'competitive_inhibition', 'Competitive inhibition (orthosteric)',
                    'derived', 'binding_mode',
                    'Displaces natural substrate; surmountable'),
    BitDefinition(177, 'C', 'non_competitive', 'Non-competitive / uncompetitive inhibition',
                    'derived', 'binding_mode',
                    'Distinct from substrate site; insurmountable'),
    BitDefinition(178, 'C', 'allosteric_positive', 'Positive allosteric modulation (PAM)',
                    'derived', 'binding_mode',
                    'Enhances endogenous agonist response'),
    BitDefinition(179, 'C', 'allosteric_negative', 'Negative allosteric modulation (NAM)',
                    'derived', 'binding_mode',
                    'Reduces endogenous agonist response'),
    BitDefinition(180, 'C', 'covalent_reversible', 'Reversible covalent binding',
                    'derived', 'binding_mode',
                    'Cyanoacrylamides, boronic acids'),
    BitDefinition(181, 'C', 'covalent_irreversible', 'Irreversible covalent binding',
                    'derived', 'binding_mode',
                    'Acrylamides targeting Cys; duration-of-action'),
    BitDefinition(182, 'C', 'mechanism_based_inhibition', 'Mechanism-based inhibition (suicide substrate)',
                    'derived', 'binding_mode',
                    'Enzyme activates inhibitor; time-dependent'),
    BitDefinition(183, 'C', 'transition_state_analog', 'Transition state analog binding',
                    'derived', 'binding_mode',
                    'Extreme affinity; enzyme mechanism mimicry'),
    BitDefinition(184, 'C', 'fragment_bindable', 'Fragment screening validated',
                    'derived', 'binding_mode',
                    'Hot spots identified by fragment-based methods'),
    BitDefinition(185, 'C', 'peptide_binding_groove', 'Peptide-binding groove',
                    'pocket', 'binding_mode',
                    'Extended shallow groove; peptidomimetics'),
    BitDefinition(186, 'C', 'dna_rna_binding_site', 'DNA/RNA binding site',
                    'pocket', 'binding_mode',
                    'Intercalators, groove binders'),
    BitDefinition(187, 'C', 'lipid_binding_site', 'Lipid/membrane-facing binding site',
                    'pocket', 'binding_mode',
                    'Lipophilic access from membrane'),
    BitDefinition(188, 'C', 'multi_site_binding', 'Multi-site / bivalent binding',
                    'derived', 'binding_mode',
                    'PROTAC, molecular glue, bivalent ligands'),
    BitDefinition(189, 'C', 'photoswitch_compatible', 'Pocket geometry compatible with photoswitches',
                    'derived', 'binding_mode',
                    'Azobenzene photopharmacology potential'),
    BitDefinition(190, 'C', 'exosite_binding', 'Exosite binding (remote from active site)',
                    'derived', 'binding_mode',
                    'Substrate-selective inhibition'),
    BitDefinition(191, 'C', 'interfacial_binding', 'Interfacial / molecular glue mechanism',
                    'derived', 'binding_mode',
                    'Stabilizes neo-interactions between proteins'),
]


# ==============================================================================
# MODULE D: Endogenous Ligand Type (bits 192-255)
# ==============================================================================
# Encodes WHAT the body natively puts into this binding site - the chemical
# evolutionary pressure that shaped the pocket's physicochemistry.

MODULE_D_BITS = [
    # --- Sub-block D1: Endogenous Ligand Chemical Class (bits 192-215) ---
    BitDefinition(192, 'D', 'endo_monoamine', 'Monoamine neurotransmitter (dopamine, serotonin, NE, histamine)',
                    'iuphar', 'ligand_type',
                    'Small, basic, aromatic; biogenic amines'),
    BitDefinition(193, 'D', 'endo_amino_acid_nt', 'Amino acid neurotransmitter (glutamate, GABA, glycine)',
                    'iuphar', 'ligand_type',
                    'Small, charged, polar'),
    BitDefinition(194, 'D', 'endo_acetylcholine', 'Acetylcholine',
                    'iuphar', 'ligand_type',
                    'Quaternary amine; nicotinic/muscarinic'),
    BitDefinition(195, 'D', 'endo_peptide_short', 'Short peptide (2-10 aa: enkephalins, angiotensin, oxytocin)',
                    'iuphar', 'ligand_type',
                    'Linear or cyclic peptides; flexible'),
    BitDefinition(196, 'D', 'endo_peptide_long', 'Long peptide / protein hormone (insulin, GLP-1, EPO)',
                    'iuphar', 'ligand_type',
                    'Large biologics; PPI-type binding'),
    BitDefinition(197, 'D', 'endo_steroid', 'Steroid hormone (cortisol, estrogen, testosterone, aldosterone)',
                    'iuphar', 'ligand_type',
                    'Rigid tetracyclic scaffold; lipophilic'),
    BitDefinition(198, 'D', 'endo_thyroid', 'Thyroid hormone (T3, T4)',
                    'iuphar', 'ligand_type',
                    'Iodinated amino acid derivative; NR ligand'),
    BitDefinition(199, 'D', 'endo_retinoid', 'Retinoid / vitamin A derivative',
                    'iuphar', 'ligand_type',
                    'Polyene chain; RAR/RXR ligand'),
    BitDefinition(200, 'D', 'endo_vitamin_d', 'Vitamin D / calcitriol',
                    'iuphar', 'ligand_type',
                    'Secosteroid; VDR ligand'),
    BitDefinition(201, 'D', 'endo_eicosanoid', 'Eicosanoid / prostanoid (PGE2, LTB4, thromboxane)',
                    'iuphar', 'ligand_type',
                    'Arachidonic acid derivatives; COX/LOX products'),
    BitDefinition(202, 'D', 'endo_phospholipid', 'Phospholipid / lysophospholipid (LPA, S1P)',
                    'iuphar', 'ligand_type',
                    'Lipid mediator; GPCR ligands'),
    BitDefinition(203, 'D', 'endo_fatty_acid', 'Fatty acid / endocannabinoid',
                    'iuphar', 'ligand_type',
                    'Anandamide, 2-AG; PPAR, CB1/CB2 ligands'),
    BitDefinition(204, 'D', 'endo_purine_nucleotide', 'Purine nucleotide (ATP, ADP, AMP)',
                    'iuphar', 'ligand_type',
                    'P2X (ionotropic), P2Y (metabotropic) receptors'),
    BitDefinition(205, 'D', 'endo_adenosine', 'Adenosine / nucleoside',
                    'iuphar', 'ligand_type',
                    'A1/A2A/A2B/A3 receptors; neuromodulator'),
    BitDefinition(206, 'D', 'endo_cyclic_nucleotide', 'Cyclic nucleotide (cAMP, cGMP)',
                    'iuphar', 'ligand_type',
                    'PDE substrate; intracellular second messenger'),
    BitDefinition(207, 'D', 'endo_ion_monovalent', 'Monovalent cation (Na+, K+)',
                    'iuphar', 'ligand_type',
                    'Ion channel permeant; selectivity filter'),
    BitDefinition(208, 'D', 'endo_ion_divalent', 'Divalent cation (Ca2+, Mg2+, Zn2+)',
                    'iuphar', 'ligand_type',
                    'Second messenger (Ca2+); cofactor (Zn2+, Mg2+)'),
    BitDefinition(209, 'D', 'endo_ion_anion', 'Anion (Cl-, HCO3-)',
                    'iuphar', 'ligand_type',
                    'Chloride channels; GABA-A receptor'),
    BitDefinition(210, 'D', 'endo_glucose', 'Glucose / monosaccharide',
                    'iuphar', 'ligand_type',
                    'GLUT transporters, SGLT inhibitors'),
    BitDefinition(211, 'D', 'endo_heme', 'Heme / porphyrin / iron-containing',
                    'iuphar', 'ligand_type',
                    'CYP enzymes, hemoglobin, guanylyl cyclase'),
    BitDefinition(212, 'D', 'endo_cofactor', 'Cofactor (NAD+, FAD, CoA, PLP)',
                    'iuphar', 'ligand_type',
                    'Metabolic enzyme cofactor binding site'),
    BitDefinition(213, 'D', 'endo_dna_rna', 'DNA or RNA as substrate',
                    'derived', 'ligand_type',
                    'Topoisomerase, polymerase, helicase'),
    BitDefinition(214, 'D', 'endo_protein_substrate', 'Protein as substrate (kinase, protease)',
                    'derived', 'ligand_type',
                    'Protein-protein interaction at active site'),
    BitDefinition(215, 'D', 'endo_no_known_ligand', 'No known endogenous ligand (orphan target)',
                    'derived', 'ligand_type',
                    'Orphan GPCR, orphan NR, uncharacterized'),

    # --- Sub-block D2: Endogenous Ligand Properties (bits 216-231) ---
    BitDefinition(216, 'D', 'native_mw_very_small', 'Native ligand MW < 100 Da',
                    'derived', 'ligand_properties',
                    'Ions, amino acids, very small metabolites'),
    BitDefinition(217, 'D', 'native_mw_small', 'Native ligand MW 100-300 Da',
                    'derived', 'ligand_properties',
                    'Neurotransmitters, nucleosides, steroids'),
    BitDefinition(218, 'D', 'native_mw_medium', 'Native ligand MW 300-600 Da',
                    'derived', 'ligand_properties',
                    'Eicosanoids, phospholipids, cofactors'),
    BitDefinition(219, 'D', 'native_mw_large', 'Native ligand MW 600-5000 Da',
                    'derived', 'ligand_properties',
                    'Peptides, cyclic peptides'),
    BitDefinition(220, 'D', 'native_mw_macromolecule', 'Native ligand MW > 5000 Da',
                    'derived', 'ligand_properties',
                    'Protein hormones, growth factors'),
    BitDefinition(221, 'D', 'native_lipophilic', 'Native ligand is lipophilic (logP > 2)',
                    'derived', 'ligand_properties',
                    'Steroids, eicosanoids, endocannabinoids'),
    BitDefinition(222, 'D', 'native_hydrophilic', 'Native ligand is hydrophilic (logP < 0)',
                    'derived', 'ligand_properties',
                    'Amino acids, nucleotides, ions'),
    BitDefinition(223, 'D', 'native_amphiphilic', 'Native ligand is amphiphilic',
                    'derived', 'ligand_properties',
                    'Phospholipids, bile acids'),
    BitDefinition(224, 'D', 'native_charged_positive', 'Native ligand positively charged at pH 7.4',
                    'derived', 'ligand_properties',
                    'Acetylcholine, histamine, dopamine'),
    BitDefinition(225, 'D', 'native_charged_negative', 'Native ligand negatively charged at pH 7.4',
                    'derived', 'ligand_properties',
                    'Glutamate, ATP, phospholipids'),
    BitDefinition(226, 'D', 'native_zwitterionic', 'Native ligand is zwitterionic',
                    'derived', 'ligand_properties',
                    'Amino acids, GABA'),
    BitDefinition(227, 'D', 'native_neutral', 'Native ligand is neutral at pH 7.4',
                    'derived', 'ligand_properties',
                    'Steroids, retinoids'),
    BitDefinition(228, 'D', 'native_rigid', 'Native ligand is rigid (< 2 rotatable bonds)',
                    'derived', 'ligand_properties',
                    'Steroids, aromatic neurotransmitters'),
    BitDefinition(229, 'D', 'native_flexible', 'Native ligand is flexible (> 5 rotatable bonds)',
                    'derived', 'ligand_properties',
                    'Peptides, fatty acids, eicosanoids'),
    BitDefinition(230, 'D', 'native_aromatic', 'Native ligand contains aromatic ring(s)',
                    'derived', 'ligand_properties',
                    'Monoamines, purines, thyroid hormones'),
    BitDefinition(231, 'D', 'native_non_aromatic', 'Native ligand is non-aromatic',
                    'derived', 'ligand_properties',
                    'Steroids, fatty acids, sugars'),

    # --- Sub-block D3: Ligand-Receptor Kinetics (bits 232-247) ---
    BitDefinition(232, 'D', 'kinetics_fast_on', 'Fast association (kon > 10^6 M-1s-1)',
                    'derived', 'kinetics',
                    'Diffusion-limited binding'),
    BitDefinition(233, 'D', 'kinetics_slow_on', 'Slow association (kon < 10^4 M-1s-1)',
                    'derived', 'kinetics',
                    'Conformational selection or deep pocket'),
    BitDefinition(234, 'D', 'kinetics_fast_off', 'Fast dissociation (koff > 10^-2 s-1; t1/2 < 1 min)',
                    'derived', 'kinetics',
                    'Rapid equilibrium; competitive dynamics'),
    BitDefinition(235, 'D', 'kinetics_slow_off', 'Slow dissociation (koff < 10^-4 s-1; t1/2 > hours)',
                    'derived', 'kinetics',
                    'Long residence time; duration of action'),
    BitDefinition(236, 'D', 'kinetics_irreversible', 'Irreversible binding (covalent, no dissociation)',
                    'derived', 'kinetics',
                    'Recovery requires new protein synthesis'),
    BitDefinition(237, 'D', 'high_affinity_native', 'High-affinity native ligand (Kd < 10 nM)',
                    'derived', 'kinetics',
                    'Drug must compete with tight endogenous ligand'),
    BitDefinition(238, 'D', 'moderate_affinity_native', 'Moderate affinity native ligand (Kd 10 nM - 1 uM)',
                    'derived', 'kinetics',
                    'Typical GPCR-amine binding range'),
    BitDefinition(239, 'D', 'low_affinity_native', 'Low affinity native ligand (Kd > 1 uM)',
                    'derived', 'kinetics',
                    'Metabolic substrates, ion channels'),
    BitDefinition(240, 'D', 'concentration_high_local', 'High local concentration of native ligand',
                    'derived', 'kinetics',
                    'Synaptic cleft, autocrine; mM range'),
    BitDefinition(241, 'D', 'concentration_low_systemic', 'Low systemic concentration of native ligand',
                    'derived', 'kinetics',
                    'Circulating hormones; pM-nM range'),
    BitDefinition(242, 'D', 'pulsatile_exposure', 'Pulsatile / episodic ligand exposure',
                    'derived', 'kinetics',
                    'Neurotransmitter release; circadian hormones'),
    BitDefinition(243, 'D', 'tonic_exposure', 'Tonic / continuous ligand exposure',
                    'derived', 'kinetics',
                    'Constitutive release; ambient concentration'),
    BitDefinition(244, 'D', 'receptor_reserve', 'Significant receptor reserve (spare receptors)',
                    'derived', 'kinetics',
                    'Maximal response at partial receptor occupancy'),
    BitDefinition(245, 'D', 'no_receptor_reserve', 'No receptor reserve (linear occupancy-response)',
                    'derived', 'kinetics',
                    'Full occupancy needed for maximal response'),
    BitDefinition(246, 'D', 'multiple_endogenous', 'Multiple endogenous ligands bind',
                    'derived', 'kinetics',
                    'Promiscuous pocket; endogenous redundancy'),
    BitDefinition(247, 'D', 'single_endogenous', 'Single / highly selective endogenous ligand',
                    'derived', 'kinetics',
                    'Dedicated receptor for one ligand'),

    # --- Sub-block D4: Pharmacological Context (bits 248-255) ---
    BitDefinition(248, 'D', 'approved_drug_exists', 'Approved drug(s) exist for this target',
                    'chembl', 'pharmacology',
                    'Validated target; clinical precedent'),
    BitDefinition(249, 'D', 'clinical_trials_active', 'Active clinical trials targeting this protein',
                    'chembl', 'pharmacology',
                    'Target under clinical investigation'),
    BitDefinition(250, 'D', 'tool_compounds_available', 'High-quality tool compounds available',
                    'chembl', 'pharmacology',
                    'Chemical probes for target validation'),
    BitDefinition(251, 'D', 'genetic_validation', 'Genetic validation (knockout/GWAS phenotype)',
                    'derived', 'pharmacology',
                    'Loss-of-function phenotype supports target'),
    BitDefinition(252, 'D', 'druggable_genome', 'In druggable genome classification',
                    'derived', 'pharmacology',
                    'Hopkins & Groom druggable genome assessment'),
    BitDefinition(253, 'D', 'polypharmacology_common', 'Polypharmacology common (multi-target drugs)',
                    'derived', 'pharmacology',
                    'Known kinase/GPCR promiscuity within family'),
    BitDefinition(254, 'D', 'resistance_mutations_known', 'Drug resistance mutations documented',
                    'derived', 'pharmacology',
                    'Kinase gatekeeper, GPCR binding site mutations'),
    BitDefinition(255, 'D', 'biomarker_available', 'Biomarker available for target engagement',
                    'derived', 'pharmacology',
                    'PD biomarker enables clinical dose optimization'),
]


# ==============================================================================
# Combined Schema
# ==============================================================================

CRAFT_SCHEMA: List[BitDefinition] = MODULE_A_BITS + MODULE_B_BITS + MODULE_C_BITS + MODULE_D_BITS

# Validate schema completeness and uniqueness
assert len(CRAFT_SCHEMA) == 256, f"Schema has {len(CRAFT_SCHEMA)} bits, expected 256"
_positions = [b.position for b in CRAFT_SCHEMA]
assert len(set(_positions)) == 256, "Duplicate bit positions found"
assert sorted(_positions) == list(range(256)), "Non-contiguous bit positions"
_names = [b.name for b in CRAFT_SCHEMA]
assert len(set(_names)) == 256, f"Duplicate bit names: {[n for n in _names if _names.count(n) > 1]}"

# Fast lookup indices
CRAFT_BIT_INDEX: Dict[int, BitDefinition] = {b.position: b for b in CRAFT_SCHEMA}
CRAFT_BIT_BY_NAME: Dict[str, BitDefinition] = {b.name: b for b in CRAFT_SCHEMA}

# Module boundaries
MODULE_RANGES = {
    'A': (0, 63),
    'B': (64, 127),
    'C': (128, 191),
    'D': (192, 255),
}

MODULE_NAMES = {
    'A': 'Membrane Topology & Localization',
    'B': 'Signal Transduction Mechanism',
    'C': 'Binding Pocket Character',
    'D': 'Endogenous Ligand Type',
}

# Sub-block boundaries (4 per module, 16 bits each)
SUBBLOCK_RANGES = {
    'A1': (0, 15, 'Subcellular Localization'),
    'A2': (16, 31, 'Transmembrane Topology'),
    'A3': (32, 47, 'Tissue Expression & BBB'),
    'A4': (48, 63, 'Protein Family Classification'),
    'B1': (64, 79, 'Primary Signaling Mechanism'),
    'B2': (80, 95, 'Downstream Pathways'),
    'B3': (96, 111, 'Signal Dynamics & Kinetics'),
    'B4': (112, 127, 'Tissue-Specific Signaling'),
    'C1': (128, 143, 'Pocket Geometry & Type'),
    'C2': (144, 159, 'Pocket Polarity & Chemistry'),
    'C3': (160, 175, 'Pocket Flexibility & Dynamics'),
    'C4': (176, 191, 'Binding Mode & Mechanism'),
    'D1': (192, 215, 'Endogenous Ligand Chemical Class'),
    'D2': (216, 231, 'Endogenous Ligand Properties'),
    'D3': (232, 247, 'Ligand-Receptor Kinetics'),
    'D4': (248, 255, 'Pharmacological Context'),
}

# Data source requirements per module
MODULE_DATA_SOURCES = {
    'A': ['uniprot', 'iuphar', 'derived'],
    'B': ['iuphar', 'derived'],
    'C': ['pocket', 'derived'],
    'D': ['iuphar', 'derived', 'chembl'],
}


def get_module_bits(module: str) -> List[BitDefinition]:
    """Get all bit definitions for a specific module."""
    start, end = MODULE_RANGES[module]
    return [b for b in CRAFT_SCHEMA if start <= b.position <= end]


def get_bits_by_source(source: str) -> List[BitDefinition]:
    """Get all bit definitions that depend on a specific data source."""
    return [b for b in CRAFT_SCHEMA if b.data_source == source]


def get_bits_by_category(category: str) -> List[BitDefinition]:
    """Get all bit definitions in a specific sub-category."""
    return [b for b in CRAFT_SCHEMA if b.category == category]


def describe_active_bits(vector, mode='binary') -> List[Dict]:
    """Return human-readable descriptions of all active (ON) bits."""
    active = []
    for i, val in enumerate(vector):
        if (mode == 'binary' and val == 1) or (mode == 'fuzzy' and val > 0.0):
            bit = CRAFT_BIT_INDEX[i]
            active.append({
                'position': i,
                'module': bit.module,
                'name': bit.name,
                'description': bit.description,
                'category': bit.category,
                'confidence': float(val) if mode == 'fuzzy' else 1.0,
                'source': bit.data_source,
                'biological_basis': bit.biological_basis,
            })
    return active
